---
title: "Loan_EDLD652_Homework2"
author: "Christopher Loan"
date: "2/22/2021"
output: rmdformats::material
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

```{r}
library(tidyverse)
library(tidytuesdayR)
library(rio)
library(countrycode)
library(gt)
library(lubridate)
```

```{r}
transit_cost <- 
  import('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-05/transit_cost.csv')
```

```{r}
country_codes <- 
  countrycode::codelist %>% 
  select(country_name = country.name.en,
         country = ecb)
```

```{r}
transit_cost <- 
  transit_cost %>% 
  left_join(country_codes, 
            by = c('country')
            )
```

# 1. Uncertainty Plot 1

```{r, fig.width= 10.5, fig.height = 7.5}
transit_cost %>% 
  mutate(real_cost = 
           as.numeric(real_cost)) %>% 
  filter(!is.na(real_cost) & 
           !is.na(country_name)) %>% 
  group_by(country_name) %>% 
  summarize(mean = mean(real_cost), 
            se = sd(real_cost)/sqrt(n())) %>% 
  ggplot(aes(x = mean, 
             y = fct_reorder(country_name, mean), 
             xmin = if_else(mean - 1.96*se < 0, 0, mean - 1.96*se), 
             xmax = mean + 1.96*se)) + 
  geom_errorbar() +
  geom_point(color = 'cornflowerblue') + 
  theme_minimal(base_size = 18) + 
  scale_x_continuous(breaks = 
                       c(0, 
                         15000, 
                         30000, 
                         45000, 
                         60000, 
                         75000, 
                         100000), 
                     expand = c(0,0)
                     ) +
  labs(x = 'Real Cost (in millions of dollars)', 
       y = 'Country', 
       title = 'Cost to build transit systems varying across country', 
       caption = 
         'Data provided through #tidytuesday by the Transit Cost Project'
       ) +
  theme(panel.grid.minor = element_blank(), 
        panel.grid.major.y = element_blank(), 
        plot.caption = element_text(hjust = 0.5))
```

# 2. Uncertainty Plot 2

```{r, fig.width= 10.5, fig.height = 7.5}
transit_cost %>% 
  mutate(real_cost = as.numeric(real_cost)) %>% 
  filter(!is.na(real_cost) 
         & !is.na(country_name)) %>% 
  group_by(country_name) %>% 
  mutate(mean = mean(real_cost), 
         n = n(),
         se = if_else(n == 1, 0, sd(real_cost)/sqrt(n))) %>% 
  ggplot(aes(
    x = real_cost, 
    y = fct_reorder(country_name, mean))) + 
  geom_jitter(color = 'cornflowerblue', 
              height = 0, 
              alpha = 0.4) + 
  geom_boxplot(color = 'gray70', 
               alpha = 0.7, 
               outlier.shape = NA) + 
  geom_point(aes(x = mean, 
                 y = fct_reorder(country_name, mean), 
                 size = se), 
             shape = 21, 
             color = 'coral3') +
  theme_minimal(base_size = 15) + 
  scale_x_continuous(breaks = 
                       c(0, 
                         15000, 
                         30000, 
                         45000, 
                         60000, 
                         75000), 
                     expand = c(0,0)) +
  labs(x = 'Real Cost (in millions of dollars)', 
       y = 'Country', 
       title = 'Cost to build transit systems varying across country', 
       size = 'Standard Error of the Mean',
       caption = 'Average cost per country shown with hollow points
       Data provided through #tidytuesday by the Transit Cost Project') +
  theme(panel.grid.minor = element_blank(), 
        panel.grid.major.y = element_blank(), 
        plot.caption = element_text(hjust = 0.5), 
        legend.position = 'bottom')
```

# 3. Fitting the model & plotting log odds

```{r}
crime <- import(here::here('Data','crime.csv')) %>% 
  janitor::clean_names()
```

```{r}
model_data <- crime %>% 
  mutate(neighborhood_id = 
           relevel(factor(neighborhood_id), ref = "barnum"))
```

```{r}
m <- glm(is_crime ~ neighborhood_id, 
         data = model_data,
         family = "binomial")
```

```{r}
tidied <-  m %>% 
  broom::tidy() %>% 
  mutate(odds = exp(estimate))
```

```{r}
barnum_west <- tidied %>% 
  filter(term == 'neighborhood_idbarnum-west')
```

```{r, fig.width= 10.5, fig.height = 7.5}
plot_dat <- data.frame(
  x = qnorm(ppoints(20), 
      mean = barnum_west$estimate, 
      sd = barnum_west$std.error)
  ) %>% 
  mutate(filler = ifelse(x <= 0, '#590AA8', '#2B8D5C'))

temp_dat <- 
  tibble(label = 
           c('Predicted cases where
             crime is more probable
             in West-Barnam', 
             'Predicted cases where
             crime more probable
             in Barnam'), 
         x = c(-0.07, 0.06), 
         y = c(0.8, 0.7), 
         fill = c('#590AA8', '#2B8D5C'))

plot_dat %>% 
  ggplot() + 
  geom_dotplot(aes(x = x, fill = filler), binwidth = 0.02) +
  scale_fill_identity(guide = 'none') +
  geom_vline(aes(xintercept = 0), color = 'darkred', size = 2) + 
  theme(panel.grid.major.y = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_line(color = 'gray70'),
        panel.background = element_rect(fill = 'white'),
        axis.line.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()) +
  labs(title = 
         'Probability of differential crime rates between neighborhoods',
       subtitle = 'West-Barnam compared to Barnum',
       y = NULL,
       x = 'Difference in log odds of a crime being committed',
       caption = 'Each circle represents 5% probability') +
  geom_label(data = temp_dat,
           inherit.aes = F,
          aes(label = label,
               x = x,
               y = y, 
              fill = fill),
          color = 'white',
          show.legend = F,
          label.size = 1,
          alpha = 0.8) + scale_color_identity(guide = 'none') 
```

# 4. Reproducing table

```{r}
crime %>% 
  filter(
    offense_category_id %in% c(
      'aggravated-assault', 
      'sexual-assault', 
      'murder',
      'other-crimes-against-persons') &
      district_id %in% c(1, 3, 5)) %>% 
  mutate(
    reported_date = mdy_hms(reported_date), 
    year = year(reported_date), 
    offense_category_id = 
      factor(offense_category_id, 
             levels = 
               c('aggravated-assault', 
                 'sexual-assault', 
                 'murder',
                 'other-crimes-against-persons'),
             labels = 
               c('Aggravated Assault', 
                 'Sexual Assault', 
                 'Murder',
                 'Other Crimes Against persons')),
    district_id = 
      factor(district_id, 
             labels = 
               c('District 1', 
                 'District 2', 
                 'District 3'))) %>% 
  select(district_id, 
         offense_category_id, 
         year) %>% 
  group_by(district_id, offense_category_id, year) %>% 
  summarize(n = n()) %>% 
  pivot_wider(names_from = 'year', 
              values_from = 'n') %>% 
  group_by(district_id) %>% 
  mutate_if(is.numeric , replace_na, replace = 0) %>% 
  gt() %>% 
  tab_spanner(
    label = 'Year', 
    columns = 
      vars(`2016`, 
           `2017`, 
           `2018`, 
           `2019`, 
           `2020`, 
           `2021`)) %>% 
  cols_label(offense_category_id = 'Offense') %>% 
  tab_header(
    title = md('Crimes Against Persons in Denver: 2014 to Present'), 
    subtitle = md('*Sample of three districts*')) %>% 
  tab_source_note(
    source_note = 
      md('Denver Crime Data Distributed via [Kaggle](https://www.kaggle.com/paultimothymooney/denver-crime-data)'))
```

